window.PROTOTYPE_DATA = {
  users: [],
  operators: [
    { id: 'op-01', username: 'edilson.souza', name: 'EDILSON COIMBRA DE SOUZA', initials: 'ES', area: 'CAFÉ CRU', function: 'Operador de Processos', shift: '', score: 94, status: 'Ativo', coordinator: 'Michelle Faria' },
    { id: 'op-02', username: 'felipe.simoes', name: 'FELIPE JUSTINO SIMOES', initials: 'FS', area: 'CAFÉ CRU', function: 'Operador de Processos', shift: '', score: 90, status: 'Ativo', coordinator: 'Michelle Faria' },
    { id: 'op-03', username: 'fernando.santos', name: 'FERNANDO JOSE DOS SANTOS', initials: 'FS', area: 'CAFÉ CRU', function: 'Operador de Processos', shift: '', score: 88, status: 'Ativo', coordinator: 'Michelle Faria' },
    { id: 'op-04', username: 'jose.medeiros', name: 'JOSE ROBERTO DE MEDEIROS', initials: 'JM', area: 'CAFÉ CRU', function: 'Operador de Processos', shift: '', score: 92, status: 'Ativo', coordinator: 'Michelle Faria' },
    { id: 'op-05', username: 'luiz.souza', name: 'LUIZ FELIPE DE SOUZA', initials: 'LS', area: 'CAFÉ CRU', function: 'Operador de Processos', shift: '', score: 89, status: 'Ativo', coordinator: 'Michelle Faria' },
    { id: 'op-06', username: 'luiz.nascimento', name: 'LUIZ LAURENCO DO NASCIMENTO', initials: 'LN', area: 'CAFÉ CRU', function: 'Operador de Processos', shift: '', score: 87, status: 'Ativo', coordinator: 'Michelle Faria' },
    { id: 'op-07', username: 'nilton.costa', name: 'NILTON FERREIRA DA COSTA', initials: 'NC', area: 'CAFÉ CRU', function: 'Operador de Processos', shift: '', score: 91, status: 'Ativo', coordinator: 'Michelle Faria' },
    { id: 'op-08', username: 'thais.souza', name: 'THAIS OLIVEIRA SOUZA', initials: 'TS', area: 'CAFÉ CRU', function: 'Operador de Processos', shift: '', score: 93, status: 'Ativo', coordinator: 'Michelle Faria' },
    { id: 'op-09', username: 'alex.teixeira', name: 'ALEX SANDRO ALVES TEIXEIRA', initials: 'AT', area: 'MOAGEM', function: 'Operador de Processos', shift: '', score: 90, status: 'Ativo', coordinator: 'Michelle Faria' },
    { id: 'op-10', username: 'daniel.madureira', name: 'DANIEL ALMEIDA MADUREIRA', initials: 'DM', area: 'MOAGEM', function: 'Operador de Processos', shift: '', score: 89, status: 'Ativo', coordinator: 'Michelle Faria' },
    { id: 'op-11', username: 'deivison.chaves', name: 'DEIVISON SOUZA ALVES CHAVES', initials: 'DC', area: 'MOAGEM', function: 'Operador de Processos', shift: '', score: 88, status: 'Ativo', coordinator: 'Michelle Faria' },
    { id: 'op-12', username: 'rafael.santos', name: 'RAFAEL DA SILVA SANTOS', initials: 'RS', area: 'TORRADOR', function: 'Operador de Processos', shift: '', score: 95, status: 'Ativo', coordinator: 'Michelle Faria' },
    { id: 'op-13', username: 'eduardo.candido', name: 'EDUARDO LUIS CANDIDO', initials: 'EC', area: 'TORRADOR', function: 'Operador de Processos', shift: '', score: 92, status: 'Ativo', coordinator: 'Michelle Faria' },
    { id: 'op-14', username: 'edvaldo.silva', name: 'EDVALDO RENER DA SILVA', initials: 'ES', area: 'TORRADOR', function: 'Operador de Processos', shift: '', score: 90, status: 'Ativo', coordinator: 'Michelle Faria' },
    { id: 'op-15', username: 'ivomar.costa', name: 'IVOMAR LOPES COSTA', initials: 'IC', area: 'TORRADOR', function: 'Operador de Processos', shift: '', score: 91, status: 'Ativo', coordinator: 'Michelle Faria' },
    { id: 'op-16', username: 'joao.rodrigues', name: 'JOAO PEDRO ALVES RODRIGUES', initials: 'JR', area: 'TORRADOR', function: 'Operador de Processos', shift: '', score: 89, status: 'Ativo', coordinator: 'Michelle Faria' },
    { id: 'op-17', username: 'vinicius.oliveira', name: 'VINICIUS RAMOS DE OLIVEIRA', initials: 'VO', area: 'TORRADOR', function: 'Operador de Processos', shift: '', score: 88, status: 'Ativo', coordinator: 'Michelle Faria' },
    { id: 'op-18', username: 'edvan.santos', name: 'EDVAN HENRIQUE PIRES SANTOS', initials: 'ES', area: 'TORRADOR', function: 'Operador de Processos', shift: '', score: 94, status: 'Ativo', coordinator: 'Michelle Faria' },
    { id: 'coord-01', username: 'michellefaria', name: 'MICHELLE FARIA', initials: 'MF', area: 'COORDENAÇÃO', function: 'Coordenadora', shift: '', score: 100, status: 'Ativo', coordinator: 'Michelle Faria' }
  ],
  months: ['Nov', 'Dez', 'Jan', 'Fev', 'Mar', 'Abr'],
  metrics: [
    { id: 'jornada', title: 'Faltas / Jornada', icon: '◷', value: '98%', detail: 'Meta 95%', trend: '+3,2%', tone: 'green', values: [91, 93, 94, 96, 95, 98] },
    { id: 'etiquetas', title: 'Etiquetas', icon: '◇', value: '1.248', detail: 'Meta 1.200', trend: '+4%', tone: 'red', values: [78, 82, 87, 90, 94, 100] },
    { id: 'bos', title: 'BOS', icon: '▣', value: '36', detail: 'Meta 40', trend: '90% atingido', tone: 'coffee', values: [62, 70, 75, 82, 86, 90] },
    { id: 'bosq', title: 'BOSQ', icon: '✓', value: '92%', detail: 'Meta 90%', trend: '+2 p.p.', tone: 'green', values: [80, 84, 86, 88, 91, 92] },
    { id: 'ideias', title: 'Ideias de melhoria', icon: '✦', value: '18', detail: 'Meta 20', trend: '5 implementadas', tone: 'gold', values: [40, 55, 48, 65, 78, 90] },
  ],
  journey: [
    { date: '02/04/2026', day: 'Quinta-feira', status: 'Horário administrativo', hours: '08:00', note: 'Integração de segurança' },
    { date: '03/04/2026', day: 'Sexta-feira', status: 'Dia compensado', hours: '08:00', note: 'Compensação registrada' },
    { date: '07/04/2026', day: 'Terça-feira', status: 'Hora extra', hours: '10:30', note: 'Apoio ao inventário' },
    { date: '10/04/2026', day: 'Sexta-feira', status: 'Atraso', hours: '07:42', note: 'Justificado pela liderança' },
    { date: '15/04/2026', day: 'Quarta-feira', status: 'Folga aniversariante', hours: '00:00', note: 'Benefício utilizado' },
    { date: '21/04/2026', day: 'Terça-feira', status: 'Folga', hours: '00:00', note: 'Escala mensal' },
  ],
  ideas: { registered: 18, analysis: 6, approved: 8, implemented: 5, goal: 20 },
};
